name: Web application publish to k8s

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
        default: ""
      node-version:
        required: true
        type: string
        default: "20"
      app-namespace:
        required: true
        type: string
        default: "reddwarf-pro"
      app-name:
        required: true
        type: string
        default: "demo-app"
      app-tag:
        required: false
        type: string
        default: "default"

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Check tag code
        if: ${{ inputs.app-tag != 'default' }}
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ inputs.app-tag }}
          fetch-depth: 0
      - name: Checkout
        if: ${{ inputs.app-tag == 'default' }}
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Build React App
        run: |
          npm install
          npm run build
        env:
          CI: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKER_REPO_USER_NAME }}
          password: ${{ secrets.ALIYUN_DOCKER_REPO_USER_PASSWORD }}

      - name: Build image push to aliyun
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/${{ inputs.app-namespace }}/${{ inputs.app-name }}:${{ github.sha }} 
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          push: true
    
        # https://github.com/steebchen/kubectl
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment/${{ inputs.app-name }} ${{ inputs.app-name }}=registry.cn-hongkong.aliyuncs.com/${{ inputs.app-namespace }}/${{ inputs.app-name }}:${{ github.sha }} -n ${{ inputs.app-namespace }}

      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0 # specify kubectl binary version explicitly
          command: rollout status deployment/${{ inputs.app-name }} -n ${{ inputs.app-namespace }}





