name: Web application publish to k8s

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
        default: ""
      node-version:
        required: true
        type: string
        default: "20"

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}





